//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mocs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mocs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Operating state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LED_CELL {
            get {
                return ResourceManager.GetString("LED_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LED_DEVICE {
            get {
                return ResourceManager.GetString("LED_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LED_ERROR {
            get {
                return ResourceManager.GetString("LED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LED_NETWORK {
            get {
                return ResourceManager.GetString("LED_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_1 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_10 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_11 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_12 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_13 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for permission to drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_20 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obstacle stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_21 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_MUORDER_STATUS_30 {
            get {
                return ResourceManager.GetString("MLD_MUORDER_STATUS_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown,offline automatic,online automatic,manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLD_OPE_MODE {
            get {
                return ResourceManager.GetString("MLD_OPE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remaining charge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_CHARGE {
            get {
                return ResourceManager.GetString("MLH_CHARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_FLOOR {
            get {
                return ResourceManager.GetString("MLH_FLOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transport status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_MUORDER_STATUS {
            get {
                return ResourceManager.GetString("MLH_MUORDER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MU Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_NAME {
            get {
                return ResourceManager.GetString("MLH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_OPE_MODE {
            get {
                return ResourceManager.GetString("MLH_OPE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_POINT_NAME {
            get {
                return ResourceManager.GetString("MLH_POINT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_X {
            get {
                return ResourceManager.GetString("MLH_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   y point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MLH_Y {
            get {
                return ResourceManager.GetString("MLH_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking the status of MU. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_CHECK_MU {
            get {
                return ResourceManager.GetString("MSG_CELL_CHECK_MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is in control operation (earthquake). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_EARTHQUAKE {
            get {
                return ResourceManager.GetString("MSG_CELL_EARTHQUAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is in control operation (fire). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_FIRE {
            get {
                return ResourceManager.GetString("MSG_CELL_FIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is something wrong with the MU. Check the display of the MU list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_MU_ERROR {
            get {
                return ResourceManager.GetString("MSG_CELL_MU_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I have an offline MU. Check the display of the MU list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_MU_OFF {
            get {
                return ResourceManager.GetString("MSG_CELL_MU_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are offline MUs and abnormal MUs. Check the display of the MU list. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_MU_OFF_ERROR {
            get {
                return ResourceManager.GetString("MSG_CELL_MU_OFF_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All MUs are online and normal. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_MU_OK {
            get {
                return ResourceManager.GetString("MSG_CELL_MU_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CELL is not running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_NOT_RUNNING {
            get {
                return ResourceManager.GetString("MSG_CELL_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is in normal operation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_RUNNING {
            get {
                return ResourceManager.GetString("MSG_CELL_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CELL is stopped working. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_STOPPED {
            get {
                return ResourceManager.GetString("MSG_CELL_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The system has stopped (cannot be continued). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_CELL_SYSTEM_STOPPED {
            get {
                return ResourceManager.GetString("MSG_CELL_SYSTEM_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MU List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_MU_LIST {
            get {
                return ResourceManager.GetString("TITLE_MU_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_SYSTEM_STATUS {
            get {
                return ResourceManager.GetString("TITLE_SYSTEM_STATUS", resourceCulture);
            }
        }
    }
}
